<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <Product>QY Player</Product>
    <Company>QY Player</Company>
    <Version>0.1.0</Version>
    <Copyright>Copyright (c) 2026 QY Player</Copyright>
  </PropertyGroup>

</Project>
